### ISSUE TITLE
Wrong API call on bittrex.v3.get_market_summary

### ISSUE THREAD

**Issue by Timothee1** [kkristof200/py_bittrex_api#12]
Hi

It looks like bittrex.v3.get_market_summary is using the same API call as bittrex.v3.get_market. Therefore the result is identical.
See:  GET /markets/{marketSymbol}  vs.  GET /markets/{marketSymbol}/summary

Regards

**Comment by kkristof200** [comment]
Hey,
Updated/published on pypi. (v0.0.20)

**Comment by Timothee1** [comment]
Perfect, thank you
