### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by sstercan** [kkristof200/py_bittrex_api#2]
when i want to ping or other reqs i get an error similar to below
  
File "/usr/local/lib/python3.7/site-packages/bittrex_api/v3.py", line 53, in ping
    method=RequestMethod.GET
  File "/usr/local/lib/python3.7/site-packages/bittrex_api/v3.py", line 1600, in __request
    headers=headers,
UnboundLocalError: local variable 'headers' referenced before assignment

what is problem with this?

**Comment by kkristof200** [comment]
@sstercan, check it out now and tell me if it did work

**Comment by sstercan** [comment]
thank you :) it's ok. lot's of endpoint checked and they are running fluently. but some of them returns

https://api.bittrex.com/v3/balances
401 {"code":"INVALID_TIMESTAMP"}

**Comment by kkristof200** [comment]
Will check it. Thanks for reporting. What are the other endpoints that return this?

**Comment by kkristof200** [comment]
@sstercan Updated the code, for me it solved the issue. Check it out and tell me if it did work for you

**Comment by sstercan** [comment]
it's ok :) thank you
