### ISSUE TITLE
401 {"code":"INVALID_CONTENT_HASH"} in post_order

### ISSUE THREAD

**Issue by sstercan** [kkristof200/py_bittrex_api#3]
Hi, i got 
401 {"code":"INVALID_CONTENT_HASH"}
error in post_order
example order dict 
{<Keys.MARKET_SYMBOL: 'marketSymbol'>: 'SC-BTC', <Keys.DIRECTION: 'direction'>: 'SELL', <Keys.ORDER_TYPE: 'type'>: 'LIMIT', <Keys.TIME_IN_FORCE: 'timeInForce'>: 'GOOD_TIL_CANCELLED', <Keys.QUANTITY: 'quantity'>: 3000.0, <Keys.CEILING: 'ceiling'>: None, <Keys.LIMIT: 'limit'>: '0.00000030', <Keys.CLIENT_ORDER_ID: 'clientOrderId'>: None, <Keys.USE_AWARDS: 'useAwards'>: None}

**Comment by kkristof200** [comment]
upgrade to v0.0.9 and tell me if it's working

**Comment by sstercan** [comment]
it's ok now. thank you
