### ISSUE TITLE
Cannot Get Candle Data 

### ISSUE THREAD

**Issue by slhawk98** [kkristof200/py_bittrex_api#5]
I cannot get candle data.
Main Error: 'str' object has no attribute 'value'
See my code below

CODE
from bittrex_api.bittrex import Bittrex
from bittrex_api.v3 import *

bittrex = BittrexV3(config.API_KEYx, config.API_SECRETx, debug_level=3)
bittrex.REVERSE_MARKET_NAMES=False
``
print(bittrex.get_recent_candles(
    market='AEON-BTC',
    candle_interval='DAY_1'
)) 

ERROR
ptl2@ptl2-opt:~/Documents/proj/full_stack_bitx$ /bin/python3 /home/ptl2/Documents/proj/full_stack_bitx/populate_prices_bitx.py
Traceback (most recent call last):
  File "/home/ptl2/Documents/proj/full_stack_bitx/populate_prices_bitx.py", line 38, in <module>
    print(bittrex.get_recent_candles(
  File "/home/ptl2/.local/lib/python3.8/site-packages/bittrex_api/v3.py", line 406, in get_recent_candles
    EndPoints.MARKETS, self.__optionally_reversed_market_name(market), EndPoints.CANDLES, candle_interval.value ,EndPoints.RECENT,
AttributeError: 'str' object has no attribute 'value'
ptl2@ptl2-opt:~/Documents/proj/full_stack_bitx$

**Comment by kkristof200** [comment]
hey,
the 'candle_interval' parameter is CandleInterval type, not string so your code should be:
```python
from bittrex_api.bittrex import Bittrex
from bittrex_api.v3 import *

bittrex = BittrexV3(config.API_KEYx, config.API_SECRETx, debug_level=3)
bittrex.REVERSE_MARKET_NAMES=False

print(
    bittrex.get_recent_candles(
        market='AEON-BTC',
        candle_interval=CandleInterval.DAY_1
    )
)
```
