### ISSUE TITLE
401 {"code":"INVALID_SIGNATURE"} when cancel order

### ISSUE THREAD

**Issue by NGVIN** [kkristof200/py_bittrex_api#6]
Hi, 

When I try to cancel the order with cancel_order(orderID), I keep getting 401 {"code":"INVALID_SIGNATURE"}. I have checked the orderID multiple times, and it is correct. I am even able to get_order_by_id(orderID). Please let me know if you have an idea? Thanks!

**Comment by NGVIN** [comment]
I figured it out. In bittrex_requests.py line 107, it should be "requests.delete" instead of "requests.post"

**Comment by kkristof200** [comment]
Hi @NGVIN ,

Thanks for fixing it. Just updated the code and published it on pip.
