### ISSUE TITLE
get_balance return error 400

### ISSUE THREAD

**Issue by goshiz** [kkristof200/py_bittrex_api#8]
Hi,

When trying to call response=self.bittrex.get_orderbook(market=symbol, depth=1)

https://api.bittrex.com/v3/markets/BTC-USDT/orderbook?depth=1
400 {"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures.","data":{"invalidRequestParameter":"Keys.DEPTH"}}

url look fine and working on postman.

**Comment by kkristof200** [comment]
bittrex = BittrexV3('YOUR_API_KEY', 'YOUR_SECRET_KEY', reverse_market_names=False)

**Comment by goshiz** [comment]
Nope, it's not the same issue.

look like "Keys.DEPTH" is not interpreted and replace by "depth" in params, even with the file imported.

**Comment by kkristof200** [comment]
Update the lib. It should work now.

**Comment by goshiz** [comment]
Thanks, that's perfect.
