### ISSUE TITLE
401 {"code":"INVALID_SIGNATURE"} when request has query params

### ISSUE THREAD

**Issue by goshiz** [kkristof200/py_bittrex_api#9]
Hi,

Having another issue.

/balances is working fine
/orders/closed is working fine
/orders/closed?marketSymbol=BTC-USDT is not working with a 401 {"code":"INVALID_SIGNATURE"}

I wonder if we need a treatment on URL before signing the request on v3.py line 1603.

**Comment by kkristof200** [comment]
Solved it, update the lib. Also I set the 'reverse_market_names' default value to True, because v3 still reverses market names

**Comment by goshiz** [comment]
Thanks. You rock.
